### ISSUE TITLE
Price import module problem

### ISSUE THREAD

**Issue by skyriakou** [sphereio/sphere-stock-import#100]
### Support reference number
https://jira.commercetools.com/browse/SUPPORT-7785

**Comment by VineetKumarKushwaha** [comment]
```
var csvParserPriceInstance = new CsvParserPrice(....);

csvParserPriceInstance.getCustomTypeDefinition.cache.clear(); // This line will clear the cache.
```

As discussed and issue is resolved with the above solution  given by [~daniel.eriksson@commercetools.de], there is no need to do any code fixes. So Please consider it as resolved.
