### ISSUE TITLE
v3.0.4 throws error while installing in yarn workspaces

### ISSUE THREAD

**Issue by Tobi-mmt** [sphereio/sphere-stock-import#103]
### Support reference number

none

### Description

Same as https://github.com/sphereio/sphere-node-product-csv-sync/issues/294
I use yarn as my package manager and i have a monorepo and use yarn workspaces

The project structure looks like this:

```
--package.json
--yarn.lock
--subfolder1
  |--package.json
--subfolder2
  |--package.json
```
So all the subfolders have a package.json but the lock file is only in the root. That's how yarn organizes workspaces.
If I add the `sphere-stock-import` package in **version 3.0.4** to the path `subfolder1/package.json` and run `yarn install` the following error occures on all enviroments (CI and locally): (version 3.0.3 works well)

```
yarn install
/usr/bin/yarn
yarn install v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.2: The platform "linux" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
error /home/runner/work/path/to/repo/node_modules/sphere-stock-import: Command failed.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Exit code: 1
Command: npx npm-force-resolutions
Arguments: 
Directory: /home/runner/work/path/to/repo/node_modules/sphere-stock-import
Output:
npx: installed 5 in 5.955s
ENOENT: no such file or directory, open './package-lock.json'
```

### Expected Behavior

Should work the same way as the version 3.0.3 without throwing an error while installing

### Current Behavior

Throws error like written above.

### Context

I just want to update from 3.0.3 to 3.0.4. Does not work with this error.

### Possible Solution

Remove command `npx npm-force-resolutions` from preinstall script and maybe resolve the vulnerable dependencies directly in the `package-lock.json`?

**Comment by daern91** [comment]
Thanks a lot for such a well-written issue!

@VineetKumarKushwaha, could you please have a look at this? Seems like it got introduced with PR https://github.com/sphereio/sphere-stock-import/pull/101

**Comment by VineetKumarKushwaha** [comment]
@daern91 I checked the issue and need some more time to fix this in better way. We cannot fix in the package-lock.json as we package-lock.json update automatically from renovate. Correct me If I am wrong.

**Comment by daern91** [comment]
I see, that makes sense to me @VineetKumarKushwaha. Do you think reverting the changes and publishing as `v3.0.5` makes sense in the meanwhile?

**Comment by VineetKumarKushwaha** [comment]
Release new patch version and verified by installing globaly with npm and yarn both.
@Tobi-mmt  Please reopen if you still get error after updating to the latest.
