### ISSUE TITLE
Add support for json files

### ISSUE THREAD

**Issue by emtii** [sphereio/sphere-stock-import#32]
Additionally to xml and csv I would love to see support for json. So I can use that lib together with sphere-product-import when I already prepared my code to create some json for that lib / cli.

**Comment by emmenko** [comment]
Close this because you should use [`sphere-node-cli`](https://github.com/sphereio/sphere-node-cli#commands) for JSON imports.

```bash
$ sphere import -p my-project -t stock -f stocks.json
```

See also https://github.com/sphereio/sphere-product-import/issues/40#issuecomment-137545832

**Comment by emmenko** [comment]
I've updated the readme with a link to the sphere-node-cli.
