### ISSUE TITLE
stock-import doesn't exit with code 1 when it fails

### ISSUE THREAD

**Issue by ngoodarzi** [sphereio/sphere-stock-import#59]
### Description
tried the stock-import command with an invalid sku but it exits with code 0!

### Expected Behavior
return code should be 1 (or non-zero), when the it fails for any reason.

### Current Behavior
{ data: {}, project_key: 'csv-connector-test-30' } 'Stock entries to process: 1'
{ data: {},
  project_key: 'csv-connector-test-30',
  filename: 'stock.csv' } 'Summary: nothing to do, everything is fine'

No update because sku is invalid but the return code is 0

### Context
There is no way to find if the command succeeded or failed!

**Comment by wizzy25** [comment]
Just had a look at this and it seems the platform creates stocks regardless of if the sku is matched with a product variant, so the module is actually not failing. Or how else do you mean by: 
> No update because sku is invalid

**Comment by ngoodarzi** [comment]
@wizzy25 Oh! I see the problem. Inventory entries are created even if the product/variant doesn't exist! OK then I close this ticket. Thanks.
