### ISSUE TITLE
Add a parameter for deletion of zero quantity inventory entries during import

### ISSUE THREAD

**Issue by junajan** [sphereio/sphere-stock-import#60]
### Description
On one project we want to import new inventory entries and delete those entries which have zero quantity.

### Expected Behavior
It can go through new entries and if the quantity is 0 it would delete an entry from API.

### Current Behavior
Not implemented currently.

### Possible Solution
We can add `removeZeroInventories` parameter which will trigger the deletion.

**Comment by skyriakou** [comment]
@junajan  Is this still relevant issue? Thanks

**Comment by butenkor** [comment]
@skyriakou I will turn the question around :) Is it relevant that we make it possible to reduce amount of data that API has to persist? Currently many projects have millions of 0 quantity inventories. Above suggestion might optionally allow to omit it.
