### ISSUE TITLE
The customfield column must be named as "custom" instead of "customField"

### ISSUE THREAD

**Issue by VasumathiJayakumar** [sphereio/sphere-stock-import#64]
### Description
There is a tool https://github.com/sphereio/sphere-stock-export which exports stocks in this format:
```csv
sku, quantityOnStock, customType, custom.deliveryStatement
```
But this tool takes data in this format:
```csv
sku, quantityOnStock, customType, customField.deliveryStatement
```
Also API stock object has a `custom` property so the column should be named just `custom` instead of `customField` in order to maintain consistency.

**Comment by hisabimbola** [comment]
This issue should be fixed [here](https://commercetools.github.io/nodejs/cli/inventories-exporter.html) instead 

Cc @junajan 

@VasumathiJayakumar please create the issue [here](https://github.com/commercetools/nodejs/issues/new)

**Comment by junajan** [comment]
I created an issue here https://github.com/commercetools/nodejs/issues/246

**Comment by VasumathiJayakumar** [comment]
@junajan thx a lot
