### ISSUE TITLE
Issues with quantityOnStock header

### ISSUE THREAD

**Issue by lauraluiz** [sphereio/sphere-stock-import#65]
### Description
When using it in Impex, having a CSV with `sku,quantityOnStock,supplyChannel` headers, it complains:

> { data: 'Can\'t find header \'quantity\' in \'sku,quantityOnStock,supplyChannel\'.',
  project_key: 'xxxx' } 'Oops, something went wrong when processing file (no SFTP)!'

### Expected Behavior
The error should not be shown AFAIK. A month ago I used the very same CSV and it worked fine.

Just for testing, I changed the header in the CSV from `quantityOnStock` to `quantity` and it worked fine at first but then it complained when a SKU appeared twice for different channels (which shouldn't happen either).

### Context
I'm trying to create a couple of projects with Sunrise data and I'm stuck importing the inventories because of this issue.

### Possible Solution
I saw that you have a test CSV similar to mine regarding `quantityOnStock`, so I checked that in Travis CI the build seems to be fine. Out of curiosity to see if that is still the case I re-executed the builds in Travis (last run was 2 months ago) and now they fail. But they fail because the project has expired. So now you have one more issue 😅

**Comment by hisabimbola** [comment]
Hello @lauraluiz,

Thanks for reporting this, the issue why it was not working on impex is because impex _somehow_ deployed an old version of this module. We have fixed it in impex and it should be fine now, please reopen if issue persist.

Also thanks about the project trial issue 😉  🤦‍♂️, we will fix that

**Comment by lauraluiz** [comment]
I tried again and it seems to fail because of the same reason as before :(

**Comment by hisabimbola** [comment]
Thanks for reporting @lauraluiz 

😞 deployed a new fix now, please test and close if fixed.

...and hopefully we don't have it again 🤞

**Comment by lauraluiz** [comment]
Working fine now @hisabimbola ! Thanks a lot :)
