### ISSUE TITLE
Several security vulnerabilities in sphere-stock-import detected

### ISSUE THREAD

**Issue by Babanila** [sphereio/sphere-stock-import#76]
#### Description
Security vulnerability in sphere-stock-import detected in dependencies.

#### Expected Behaviour
No security vulnerability in dependencies

#### Current Behaviour
Security vulnerabilities found are
```
54 vulnerabilities (18 low, 19 moderate, 16 high, 1 critical)
```
#### Context
Sphere-stock-import package.json

#### Possible Solution
Updating of necessary dependencies to fix vulnerabilities

**Comment by skyriakou** [comment]
issue closed with https://github.com/sphereio/sphere-stock-import/pull/80
