### ISSUE TITLE
Update Dependencies which are insecure.

### ISSUE THREAD

**Issue by moredhel** [sphereio/sphere-stock-import#95]
It seems like there are a number of vulnerabilities that are addressed in some of the automated PRs.
I depend on this library for importing & would prefer not to fork.

Thanks

**Comment by thijsgadiot** [comment]
These are the dependencies with vulnerabilities, and their usage:

set-value
Prototype Pollution
https://npmjs.com/advisories/1012
sphere-stock-import>sphere-node-sdk>sphere-node-utils>load-module-pkg>expand-pkg>normalize-pkg>map-schema>set-value

set-value
Prototype Pollution
https://npmjs.com/advisories/1012
sphere-stock-import>sphere-node-utils>load-module-pkg>expand-pkg>normalize-pkg>map-schema>set-value

set-value
Prototype Pollution
https://npmjs.com/advisories/1012
sphere-stock-import>sphere-node-sdk>sphere-node-utils>load-module-pkg>expand-pkg>normalize-pkg>map-schema>union-value>set-value

set-value
Prototype Pollution
https://npmjs.com/advisories/1012
sphere-stock-import>sphere-node-utils>load-module-pkg>expand-pkg>normalize-pkg>map-schema>union-value>set-value

csv-parse
Regular Expression Denial of Service
https://npmjs.com/advisories/1171
sphere-stock-import>csv>csv-parse

csv-parse
Regular Expression Denial of Service
https://npmjs.com/advisories/1171
sphere-stock-import>sphere-node-sdk>sphere-node-utils>csv>csv-parse

csv-parse
Regular Expression Denial of Service
https://npmjs.com/advisories/1171
sphere-stock-import>sphere-node-utils>csv>csv-parse

defaults-deep
Prototype Pollution
https://npmjs.com/advisories/778
sphere-stock-import>sphere-node-sdk>sphere-node-utils>load-module-pkg>expand-pkg>defaults-deep

defaults-deep
Prototype Pollution 
https://npmjs.com/advisories/778
sphere-stock-import>sphere-node-utils>load-module-pkg>expand-pkg>defaults-deep

**Comment by daern91** [comment]
Most of these have been fixed now. Please install latest, `v3.0.1`. Only `CSV` package left which unfortunately would need more work as it has breaking changes.

**Comment by VineetKumarKushwaha** [comment]
Remove github vulneribility warnings

current direct dependencies has some github vulnerability because of the Transitive dependencies. So we need to update below packages.

    lodash update to 4.17.12
    kind-of update to 6.0.3
    minimist to 0.2.1
    csv-parse to 4.4.6

**Comment by VineetKumarKushwaha** [comment]
Cannot update csv-parse as it is transitive dependency of csv and we are using 1.2.0 and the latest is 4+ . So it may breaking things.
