### ISSUE TITLE
CLI Stock import throws an error

### ISSUE THREAD

**Issue by skyriakou** [sphereio/sphere-stock-import#99]
### Support reference number
https://jira.commercetools.com/browse/SUPPORT-7660

**Comment by briantomkins** [comment]
customer reported that getCustomTypeDefinition.cache = {} fixes the issue. But should this not be done in the app already?

**Comment by VineetKumarKushwaha** [comment]
@briantomkins  This is because we memoize the function based on customType so they have to clear cache before running with with same customType but with different project.
I am marking it as closed.
